USE [master]
GO

/****** Object:  Database [GraphqlBookstore]    Script Date: 19/02/2020 4:41:43 PM ******/
CREATE DATABASE [GraphqlBookstore]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GraphqlBookstore', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\GraphqlBookstore.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GraphqlBookstore_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\GraphqlBookstore_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [GraphqlBookstore] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GraphqlBookstore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GraphqlBookstore] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GraphqlBookstore] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GraphqlBookstore] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GraphqlBookstore] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GraphqlBookstore] SET ARITHABORT OFF 
GO

ALTER DATABASE [GraphqlBookstore] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GraphqlBookstore] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GraphqlBookstore] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GraphqlBookstore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GraphqlBookstore] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GraphqlBookstore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GraphqlBookstore] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GraphqlBookstore] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GraphqlBookstore] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GraphqlBookstore] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GraphqlBookstore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GraphqlBookstore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GraphqlBookstore] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GraphqlBookstore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GraphqlBookstore] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GraphqlBookstore] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GraphqlBookstore] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GraphqlBookstore] SET RECOVERY FULL 
GO

ALTER DATABASE [GraphqlBookstore] SET  MULTI_USER 
GO

ALTER DATABASE [GraphqlBookstore] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GraphqlBookstore] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GraphqlBookstore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GraphqlBookstore] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GraphqlBookstore] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GraphqlBookstore] SET QUERY_STORE = OFF
GO

USE [GraphqlBookstore]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [GraphqlBookstore] SET  READ_WRITE 
GO


